from all_ones.all_ones import all_ones
from all_zeros.all_zeros import all_zeros
from passthrough.passthrough import passthrough
from addition.addition import addition
from counter.counter import counter
from sys_reset.sys_reset import sys_reset
from multiplication.multiplication import multiplication
from ram_32x4_2r_1w.ram_32x4_2r_1w import ram_32x4_2r_1w
from register_file.register_file import register_file
from macc_8x8_20.macc_8x8_20 import macc_8x8_20
